### ISSUE TITLE
[Feature] All 3 accept-all-incoming folders

### ISSUE THREAD

**Issue by gusbemacbe** [zawys/vscode-as-git-mergetool#1]
Hello @zawys !

> In that process, I will clone some of the functionality of git-mergetool, e.g. resolving delete and symbolic link merge conflicts. I'm not sure how far that covers your use case. Maybe I could also add e.g. an accept-all-incoming-in-folder command. Please open an issue for
the extension to discuss further.

For example, see the screenshot of Meld:

![image](https://user-images.githubusercontent.com/2257024/91863579-a7c7a900-ec45-11ea-8edd-0e8d03b7c800.png)

The first is @SmartFinn's Papirus icons theme, the second is @Bonandry's Yaru++ icons theme and the third is an empty folder where I will merge the orphan files (green highlights) that I will redesign and copy to the second folder.

**Comment by zawys** [comment]
I'm not sure I understand what you mean.
1. Do the folders have a common ancestor?
2. Why do you not make a copy of the first folder, do your edits in that copy and do a 2-folder comparison in between the copy and the second folder?

**Comment by zawys** [comment]
3. In which regard does Meld help you to reach you goal?

**Comment by zawys** [comment]
I will reopen the issue when sufficient information is provided.
