### ISSUE TITLE
Not working when working on Remote-SSH

### ISSUE THREAD

**Issue by dsc8x** [zawys/vscode-as-git-mergetool#5]
When I run `Start git mergetool` in VSCode then the normal merge tool from git opens in the console instead of this `vscode-as-git-mergetool` plugin.

I'm working on a remote SSH workspace.

The `~/.gitconfig` on the remote machine looks like this: 

```
[core]
	excludesFile = ~/dev/.gitignore
[merge]
	conflictstyle = merge
	tool = code
[mergetool]
	keepTemporaries = false
	keepBackup = false
[mergetool "code"]
	cmd = \"/home/epegzz/.vscode-server/bin/ea2859d4ba2f3e577a159bc91e3074c5d85c0523/node\" \"$BASE\"
```

Is it supposed to work on remote SSH workspaces?

**Comment by zawys** [comment]
What happens when you run `/home/epegzz/.vscode-server/bin/ea2859d4ba2f3e577a159bc91e3074c5d85c0523/node`? Does it launch VS Code?

**Comment by elad-eyal** [comment]
I think I got it working by configuring this in my ~/.gitconfig
```
[mergetool "code"]
    cmd = code "$BASE"
````


Note the use of `code` and not `node` in the `cmd`

**Comment by dsc8x** [comment]
@eladeyal-intel this won't work on remote SSH workspaces unfortunately

@zawys I've stopped using the plugin for now, closing this issue :)

**Comment by elad-eyal** [comment]
@epegzz For me it works fine on a remote ssh workspace. (My host is Windows and the remote is on linux). (when running "git mergetool" from the linux shell inside the integrated terminal)

BTW the `.vscode-server/bin/` is part of my `$PATH`.  Maybe something in your `.bashrc` is masking that.

**Comment by dsc8x** [comment]
Oh, did not know that `.vscode-server/bin/` has a `code` binary 👌

**Comment by zawys** [comment]
Thanks for coming back to this issue!

**Comment by HIT2022** [comment]
> @epegzz For me it works fine on a remote ssh workspace. (My host is Windows and the remote is on linux). (when running "git mergetool" from the linux shell inside the integrated terminal)
> 
> BTW the `.vscode-server/bin/` is part of my `$PATH`. Maybe something in your `.bashrc` is masking that.

Would you mind clarifying how this works on your remote workspace? I might be trying to achieve something different, but I'm using VS code on a Windows local machine and connected to a remote linux machine (where the repo exists), and VS is attempting to launch mergetool on that remote machine, whereas I'd prefer it to instead diff the remote machine's files on the local machine.

**Comment by elad-eyal** [comment]
@HITChris  since the merge command is `code` - then it would try to run the "remote" command `code` which somehow knows to open the diff on the "local" machine
