### ISSUE TITLE
Settings assistant does not work at all

### ISSUE THREAD

**Issue by mvoppen** [zawys/vscode-as-git-mergetool#6]
## Steps to reproduce

When I start VSC after installation of the extension a dialog asks me questions about setting different options.

Whenever I select 'set globally' or 'set in workspace' I get an error message (see below) and the assistant aborts.

Maybe the Extension does not support VCL on WSL?

## [Optional] screenshots

Error on running the settings assistant: "Setting Git configuration mergetool.keepTemporaries__vscode_as_git_mergetool_backup failed with: Error: Command failed: git config mergetool.keepTemporaries__vscode_as_git_mergetool_backup (unset__vscode_as_git_mergetool_backup)\nerror: invalid key: mergetool.keepTemporaries__vscode_as_git_mergetool_backup\n. \nExit code: 1; Signal: unknown. \nStdout: none\nStderr: \nerror: invalid key: mergetool.keepTemporaries__vscode_as_git_mergetool_backup\n"

## Environment

- Version of the extension: 0.13.3
- Operating system: Windows 10
- VS Code version [use Code command “Help: About”]: 
- Other installed extensions (if applicable): WSL

**Comment by zawys** [comment]
confirmed

**Comment by zawys** [comment]
Fixed in v0.14.0
